version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exam_final  # Veritabanı adı
    ports:
      - "5432:5432"  # 5432 portunu açıyoruz (PGAdmin için)
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./deniz.tar:/docker-entrypoint-initdb.d/dvdrental.tar

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # PGAdmin 5050 portunu 80 portuna yönlendiriyor
    depends_on:
      - db

volumes:
  postgres-data:
